//searchWeather

export const WEATHER_INPUT_CHANGE = 'WEATHER_INPUT_CHANGE';

//todayWeather
export const TODAY_WEATHER_REQUEST = 'TODAY_WEATHER_REQUEST';
export const TODAY_WEATHER_SUCCESS = 'TODAY_WEATHER_SUCCESS';
export const TODAY_WEATHER_FAILURE = 'TODAY_WEATHER_FAILURE';

//longTimeWeather
export const LONGTIME_WEATHER_REQUEST = 'LONGTIME_WEATHER_REQUEST';
export const LONGTIME_WEATHER_SUCCESS = 'LONGTIME_WEATHER_SUCCESS';
export const LONGTIME_WEATHER_FAILURE = 'LONGTIME_WEATHER_FAILURE';
export const DISPLAY_LONGTIME_WEATHER = 'DISPLAY_LONGTIME_WEATHER';
